pre-release-commit-message = "chore: release"
tag-message = "{{tag_name}}"
tag-name = "{{crate_name}}@v{{version}}"
consolidate-commits = false
consolidate-pushes = true
allow-branch = ["master"]
dev-version = false
